// Generated by https://quicktype.io

import { Product } from "../product";
import { Sale } from "./sale";

export interface SalesResponse {
    data: Sale[];
}


export interface Detail {
    amount:  number;
    product: Product;
}